const courseData = [
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " عر عر", courseMaster: "میو میو نیگا", price: 100000 },
  { courseName: " میو میو", courseMaster: "میو میو نیگا", price: 100000 },
];
const newsData = [
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
];
export { courseData, newsData };
