const courseData = [
  {
    courseName: "طراحی سایت",
    courseMaster: "استاد محسن اسفندیاری",
    price: 100000,
    view: 10,
    addTime: 14020210,
    like: 11,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد مهدی اصغری",
    price: 10232100,
    view: 14,
    addTime: 14020406,
    like: 12,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 10000,
    view: 13,
    addTime: 14021003,
    like: 21,
  },
  {
    courseName: "ری اکت",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 10031232000,
    view: 43,
    addTime: 14021111,
    like: 32,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد محسن اسفندیاری",
    price: 123213,
    view: 657,
    addTime: 14021221,
    like: 421,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد مهدی اصغری",
    price: 43213,
    view: 32,
    addTime: 14020110,
    like: 312,
  },
  {
    courseName: "ری اکت",
    courseMaster: "استاد حامد نظری",
    price: 645654,
    view: 543,
    addTime: 14020423,
    like: 213,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 1312,
    view: 321,
    addTime: 14021221,
    like: 321,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 3215532,
    view: 213,
    addTime: 14020805,
    like: 32,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 35325,
    view: 32,
    addTime: 14020921,
    like: 131,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 53,
    view: 12,
    addTime: 14020112,
    like: 42,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 253226257,
    view: 54,
    addTime: 14020708,
    like: 231,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 100000,
    view: 653,
    addTime: 14020915,
    like: 321,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 432432,
    view: 4324,
    addTime: 14020221,
    like: 32,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 543,
    view: 543,
    addTime: 14020723,
    like: 345,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 654,
    view: 2343,
    addTime: 14020930,
    like: 6453,
  },
  {
    courseName: "طراحی سایت",
    courseMaster: "استاد محسن اسفندیاری",
    price: 432423,
    view: 432,
    addTime: 14020529,
    like: 54,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 87667870,
    view: 4323,
    addTime: 14021127,
    like: 43,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 8907,
    view: 532,
    addTime: 14020123,
    like: 321,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 534534,
    view: 34,
    addTime: 14021212,
    like: 12,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 5435342,
    view: 43,
    addTime: 14021111,
    like: 33,
  },
  {
    courseName: "پایتون",
    courseMaster: "استاد مهدی اصغری",
    price: 4324566,
    view: 4234,
    addTime: 14020313,
    like: 213,
  },
  {
    courseName: "ری اکت",
    courseMaster: "استاد حامد نظری",
    price: 342343257,
    view: 34,
    addTime: 14020321,
    like: 2132,
  },
  {
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 87656,
    view: 432,
    addTime: 14020221,
    like: 21,
  },
];
const newsData = [
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
  { topic: "هوا", author: "فرامرز", number: 12 },
];
const masterData = [
  { id: 1, master: "استاد محمد بحرالعلوم", topic: "مدیدریت پژوهشگاه" },
  { id: 2, master: "استاد حامد نظری", topic: "مدرس دوره ی دیزاین" },
  { id: 3, master: "استاد مهدی اصغری", topic: "مدرس دوره ی ری اکت" },
  { id: 4, master: "استاد محسن اسفندیاری", topic: "مدرس دوره ی ری اکت" },
];
const courseNameData = [
  { id: 1, courseName: "پایتون" },
  { id: 2, courseName: "ری اکت" },
  { id: 3, courseName: "طراحی سایت" },
  { id: 4, courseName: "دوره اصلی" },
];
const relatedData = [
  { courseName: " میو ", courseMaster: "میو  نیگا", price: 100000 },
  { courseName: " میو ", courseMaster: "میو  نیگا", price: 100000 },
  { courseName: " میو ", courseMaster: "میو  نیگا", price: 100000 },
];
const commentData = [
  {
    text: "خووووووووووبببب بوووووووووووود",
    userName: "سجاد",
    userLogo: "https://picsum.photos/200/300",
    reply: [],
    date: "۳۰ مرداد",
  },
  {
    text: "خوب بود",
    userName: "سجاد",
    userLogo: "https://picsum.photos/200/500",
    reply: [],
    date: "۱۰ فروردین",
  },
  {
    text: "بد بود",
    userName: "اشکان محمدی اصل",
    userLogo: "https://picsum.photos/200/400",
    reply: [],
    date: " دیروز ",
  },
];
const myCourseData = [
  {
    coursePic: "https://picsum.photos/200/200",
    courseName: " میو ",
    courseMaster: "میو میو نیگا",
    term: "زمستان",
    date: "۱۴۰۲/۰۴/۲۹",
    price: 190000,
  },
  {
    coursePic: "https://picsum.photos/200/300",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "تابستان",
    date: "۱۴۰۳/۰۸/۲۰",
    price: 300000,
  },
  {
    coursePic: "https://picsum.photos/200/400",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "بهار",
    date: "۱۴۰۱/۱۲/۱۰",
    price: 400000,
  },
];
const allCourseData = [
  {
    coursePic: "https://picsum.photos/200/200",
    courseName: " میو ",
    courseMaster: "میو میو نیگا",
    term: "زمستان",
    date: "۱۴۰۲/۰۴/۲۹",
    price: 190000,
  },
  {
    coursePic: "https://picsum.photos/200/300",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "تابستان",
    date: "۱۴۰۳/۰۸/۲۰",
    price: 300000,
  },
  {
    coursePic: "https://picsum.photos/200/400",
    courseName: " میو میو",
    courseMaster: "میو میو ",
    term: "بهار",
    date: "۱۴۰۱/۱۲/۱۰",
    price: 980000,
  },
  {
    coursePic: "https://picsum.photos/200/500",
    courseName: " ها میو",
    courseMaster: "میو میو نیگا",
    term: "بهار",
    date: "۱۴۰۱/۰۷/۱۹",
    price: 1000000,
  },
  {
    coursePic: "https://picsum.photos/200/600",
    courseName: " ها ها ",
    courseMaster: "میو  نیگا",
    term: "هاا",
    date: "۱۴۰۱/۰۲/۰۳",
    price: 480000,
  },
];

export {
  courseData,
  newsData,
  masterData,
  relatedData,
  commentData,
  myCourseData,
  allCourseData,
  courseNameData,
};
